# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  We are currently not accepting any contributions to this app. You can raise a feature request from [here](https://github.com/integrations/slack/issues/new).

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors
newPRWelcomeComment: >
  Thanks for taking time to contribute! We'll check this out soon and let you know if we have any questions or feedback.
